### ISSUE TITLE
Duplication of professions when re-entering the server.

### ISSUE THREAD

**Issue by Anhelm** [Fulmineo64/Guild#7]
**Modloader**
Fabric 1.17.1
Guild 0.0.7

1. Buy a profession from a Guild Master 
2. Activate it 
3. Press J 
4. We exit the server and go back 
5. We get 2 professions
![image](https://user-images.githubusercontent.com/74124042/134286763-019c3115-aeaa-4527-96a1-c59e6b724453.png)
![image](https://user-images.githubusercontent.com/74124042/134288803-7204f4ed-7830-4b48-8282-9df942bfdf63.png)

**Comment by Anhelm** [comment]
After three re-calls, this crash begins: https://github.com/Fulmineo64/Guild/issues/6

**Comment by Fulmineo64** [comment]
Hi Anhelm,
quite an interesting problem you have here!

I deduce that this happens because you're playing with another person with the same profession as yours right?
I'll be definetely difficult to test this on my part, but with your help, I will likely be able to solve it.
I just released the v0.0.8 that adds the command "/guild reset" to remove you from this unpleasant situation.
The command removes all your quests and professions, so you should start as new.

Then I just need a list of steps to replicate the issue, the more precise the better.
Thank you.

**Comment by Anhelm** [comment]
The error remained.
Sequence of actions:
1. Go to the dedicated server
2. Write the command /guild reset
3. I'm buying a new profession
4. Activate the profession
5. Exit the server
6. We go to the server there are two professions

We have a separate server with your mod on which 10 people play, the professions of the players are the same
![Screenshot_12](https://user-images.githubusercontent.com/74124042/134323855-c9875b4e-c8b6-4d8d-987b-603b5301422b.png)
![Screenshot_13](https://user-images.githubusercontent.com/74124042/134323875-1efaacd3-d245-4b54-8ab1-f1420e6c4550.png)

**Comment by Fulmineo64** [comment]
I've double checked the code and I noticed something strange that may cause your issue.
I've compiled 2 test versions for the server, you can try them one at a time to see if they fix the problem:
[guild-fabric-0.0.8-test.zip](https://github.com/Fulmineo64/Guild/files/7210185/guild-fabric-0.0.8-test.zip)

If the problem still persists, I have the following questions:
- do the Professions double (as 2 becomes 4) or do they increase by 1 every time you connect?
- can you share a link to your modpack? (as there may be a conflict between mods)
- what happens if someone (you or another player) accepts a different profession?

Thank you again for the collaboration.

**Comment by Anhelm** [comment]
1. Professions are doubled: 1 output of them becomes 2 pieces, the second output of them becomes 4 pieces, the third output of them becomes 8 pieces and the crash begins
2. Test mods did not fix the problems
3. Customer Mods - https://drive.google.com/file/d/1AGZHlrGm4GIaki7aHCSngzwz5XTPM5-W/view?usp=sharing
4. Server Mods - https://drive.google.com/file/d/1sRZKZK87YlG4jGIPwqq33FVqG65_HjuD/view?usp=sharing
5. We checked all the players deleted the professions, only I took the profession, deleted playerdat files from the server, it didn't help

**Comment by Fulmineo64** [comment]
Hi Anhelm,
after quite a bit of searching I finally found the issue.

It's a mod conflict with the mod "LevelZ", I'll see what I can do to fix / work around this.
In the meantime if you remove the LevelZ mod it should work properly (i tested this in single player).

By the way nice modpack!
I'll keep you updated if I find a way to fix this.

**Comment by OxcydePlays** [comment]
Hi, adding in to this with a crash log. I encountered this issue with a previous version of this mo. I got it update to the newest one uploaded recently and here's the crash log for it: pastebin.com/PWgYUPQK

I checked on LevelZ's side but no updates on it yet. Hopefully we get a fix for that mod soon too.

**Comment by Fulmineo64** [comment]
Seems to be the a related problem, 
have you found some other mods that duplicate the professions?

Try with a "/guild reset" command. 
Let me know if they still duplicate.
